# Force Clang-18 + libc++ on Unix (Linux/macOS). Use via CMakePresets.json.
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

# Set the compiler to clang-18 specifically for Linux/Ubuntu
if(NOT CMAKE_C_COMPILER)
  set(CMAKE_C_COMPILER clang-18)
endif()
if(NOT CMAKE_CXX_COMPILER)
  set(CMAKE_CXX_COMPILER clang++-18)
endif()

set(_LIBCXX_FLAGS "-stdlib=libc++")

set(CMAKE_CXX_FLAGS_INIT "${CMAKE_CXX_FLAGS_INIT} ${_LIBCXX_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${CMAKE_EXE_LINKER_FLAGS_INIT} ${_LIBCXX_FLAGS}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${CMAKE_SHARED_LINKER_FLAGS_INIT} ${_LIBCXX_FLAGS}")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "${CMAKE_MODULE_LINKER_FLAGS_INIT} ${_LIBCXX_FLAGS}")

if(UNIX AND NOT APPLE)
  set(CMAKE_EXE_LINKER_FLAGS_INIT "${CMAKE_EXE_LINKER_FLAGS_INIT} -lc++ -lc++abi")
endif()
